/// Models generated by the CycloneDx JSON Specification and extensions that have been added to
/// support working with CycloneDx documents.
pub mod cyclonedx;

/// Persistence models that support storing, analyzing, and tracking software packages over time and
/// across system and organizational boundaries.
pub mod packages;

/// Persistence models that support storing,analyzing, and tracking SBOMs over time.
pub mod sboms;

/// Persistence models that support storing and managing groups of people that produce and manage
/// SBOMs.
pub mod teams;

/// Model extensions that allow cross-referencing to external systems.
pub mod xrefs;
