use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

/// Advisory : Title and location where advisory information can be obtained. An advisory is a notification of a threat to a component, service, or system.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Advisory {
    /// An optional name of the advisory.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Location where the advisory can be obtained.
    #[serde(rename = "url")]
    pub url: String,
}

impl Advisory {
    /// Title and location where advisory information can be obtained. An advisory is a notification of a threat to a component, service, or system.
    pub fn new(url: String) -> Advisory {
        Advisory {
            title: None,
            url,
        }
    }
}


