use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */
/// The vulnerability status of a given version or range of versions of a product. The statuses 'affected' and 'unaffected' indicate that the version is affected or unaffected by the vulnerability. The status 'unknown' indicates that it is unknown or unspecified whether the given version is affected. There can be many reasons for an 'unknown' status, including that an investigation has not been undertaken or that a vendor has not disclosed the status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AffectedStatus {
    #[serde(rename = "affected")]
    Affected,
    #[serde(rename = "unaffected")]
    Unaffected,
    #[serde(rename = "unknown")]
    Unknown,

}

impl ToString for AffectedStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Affected => String::from("affected"),
            Self::Unaffected => String::from("unaffected"),
            Self::Unknown => String::from("unknown"),
        }
    }
}

impl Default for AffectedStatus {
    fn default() -> AffectedStatus {
        Self::Affected
    }
}




