use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

/// Credits : Individuals or organizations credited with the discovery of the vulnerability.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Credits {
    /// The organizations credited with vulnerability discovery.
    #[serde(rename = "organizations", skip_serializing_if = "Option::is_none")]
    pub organizations: Option<Vec<crate::models::cyclonedx::OrganizationalEntity>>,
    /// The individuals, not associated with organizations, that are credited with vulnerability discovery.
    #[serde(rename = "individuals", skip_serializing_if = "Option::is_none")]
    pub individuals: Option<Vec<crate::models::cyclonedx::OrganizationalContact>>,
}

impl Credits {
    /// Individuals or organizations credited with the discovery of the vulnerability.
    pub fn new() -> Credits {
        Credits {
            organizations: None,
            individuals: None,
        }
    }
}


