use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

/// Note : A note containing the locale and content.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Note {
    /// Defines a syntax for representing two character language code (ISO-639) followed by an optional two character country code. The language code MUST be lower case. If the country code is specified, the country code MUST be upper case. The language code and country code MUST be separated by a minus sign. Examples: en, en-US, fr, fr-CA
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    #[serde(rename = "text")]
    pub text: Box<crate::models::cyclonedx::Attachment>,
}

impl Note {
    /// A note containing the locale and content.
    pub fn new(text: crate::models::cyclonedx::Attachment) -> Note {
        Note {
            locale: None,
            text: Box::new(text),
        }
    }
}


