openapi: 3.0.1
info:
  title: CycloneDx
  description: Exists only to support generation of CycloneDx 1.4 Models
  version: 0.1.0
servers:
  - url: https://localhost:6000
    variables:
      basePath:
        default: ''
paths:
  /api/v2/sbom:
    post:
      requestBody:
        $ref: '#/components/requestBodies/sbom'
      responses:
        "200":
            $ref: '#/components/responses/uploadResult'

components:
  requestBodies:
    sbom:
      content:
        application/json:
          schema:
              type: string
              oneOf:
                - $ref: 'https://gist.githubusercontent.com/DerekStrickland/9b9c4997b68b278e1f9835e235a87e52/raw/917863e9233c15af783cbab33655a53496e9e84e/cyclonedx-1.4.json'
