repos:
  - repo: https://github.com/aquia-inc/pre-commit-rust
    rev: v1.0.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
        args:
          - '--config'
          - '.gitleaks.toml'
          - '--staged'
          - '--verbose'

  - repo: local
    hooks:
      - id: cargo-test
        name: Cargo test
        entry: cargo test
        language: system
        types: [rust]
