repos:
  - repo: local
    hooks:
    -   id: fmt
        name: fmt
        description: Format files with cargo fmt.
        entry: bash ./bin/rustfmt.sh
        language: system
        files: \.rs$
        pass_filenames: false
    -   id: cargo-clippy
        name: cargo clippy
        description: Run the Clippy linter on the package.
        entry: bash ./bin/clippy.sh
        language: system
        files: \.rs$
        pass_filenames: false
    -   id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: bash ./bin/check.sh
        language: system
        files: \.rs$
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
        args:
          - '--config'
          - '.gitleaks.toml'
          - '--staged'
          - '--verbose'
