services:
  mongo:
    image: mongo:5.0.15
    ports:
      - "27017:27017"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:9.4.3
    ports:
      - "3000:3000"
