""" Constants to be used throughout the system"""

DT_API_PORT = 8080

ENRICHMENT_ID = "ENRICHMENTID"

DT_DEFAULT_ADMIN_PWD = "admin"
ENRICHMENT_ID_SQS_KEY = "enrichmentid"
FINDINGS_SQS_KEY = "findings_key"
DT_QUEUE_URL_EV = "DT_QUEUE_URL"
SBOM_BUCKET_NAME_KEY = "sbom_bucket_name"
SBOM_S3_KEY = "sbom_s3_key"
DT_API_KEY = "DT_API_KEY"
DT_API_BASE = "DT_API_BASE"
DT_ROOT_PWD = "DT_ROOT_PWD"

EMPTY_VALUE = "EMPTY"

LOAD_BALANCER_ID = "DEPENDENCY-TRACK-LOAD-BALANCER"
LOAD_BALANCER_LISTENER_ID = "DT-LB-LISTENER-ID"
LOAD_BALANCER_TARGET_ID = "DT-LB-TARGET-ID"

ALLOW_DT_PORT_SG = f"ALLOW_{DT_API_PORT}_SG"
