AWSTemplateFormatVersion: "2010-09-09"
Description: Internet, NAT, VPN, and Transit gateways for dev-harbor-network-vpc-subnets-use1.
Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: dev-harbor-network-gateways-use1
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Fn::ImportValue: dev-harbor-network-vpc-subnets-use1-VpcId
  ElasticIpA:
    Type: AWS::EC2::EIP
    Properties: {}
  NatGatewayA:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt: ElasticIpA.AllocationId
      SubnetId:
        Fn::ImportValue: dev-harbor-network-vpc-subnets-use1-SubnetPublicAId
      Tags:
        - Key: Name
          Value: dev-harbor-network-gateways-use1
    DependsOn: InternetGatewayAttachment
  ElasticIpB:
    Type: AWS::EC2::EIP
    Properties: {}
  NatGatewayB:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt: ElasticIpB.AllocationId
      SubnetId:
        Fn::ImportValue: dev-harbor-network-vpc-subnets-use1-SubnetPublicBId
      Tags:
        - Key: Name
          Value: dev-harbor-network-gateways-use1
    DependsOn: InternetGatewayAttachment
Outputs:
  InternetGatewayId:
    Description: Internet Gateway ID
    Value:
      Ref: InternetGateway
    Export:
      Name: dev-harbor-network-gateways-use1-InternetGatewayId
  NatGatewayAId:
    Description: NAT A ID
    Value:
      Ref: NatGatewayA
    Export:
      Name: dev-harbor-network-gateways-use1-NatGatewayAId
  NatGatewayAIP:
    Value:
      Ref: ElasticIpA
    Export:
      Name: dev-harbor-network-gateways-use1-NatGatewayAIP
  NatGatewayBId:
    Description: NAT B ID
    Value:
      Ref: NatGatewayB
    Export:
      Name: dev-harbor-network-gateways-use1-NatGatewayBId
  NatGatewayBIP:
    Value:
      Ref: ElasticIpB
    Export:
      Name: dev-harbor-network-gateways-use1-NatGatewayBIP
