AWSTemplateFormatVersion: "2010-09-09"
Description: Network Access Control Lists (NACLs) for dev-harbor-network-vpc-subnets-use1
Resources:
  IngressTcp80RestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 80
        To: 80
      RuleNumber: 100
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 6
      RuleAction: allow
  IngressTcp443RestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 443
        To: 443
      RuleNumber: 101
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 6
      RuleAction: allow
  IngressTcpEphemeralRestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 1024
        To: 65535
      RuleNumber: 102
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 6
      RuleAction: allow
  IngressTcpDnsRestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 53
        To: 53
      RuleNumber: 103
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 6
      RuleAction: allow
  IngressUdpDnsRestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 53
        To: 53
      RuleNumber: 104
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 17
      RuleAction: allow
  IngressUdpNtpRestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 123
        To: 123
      RuleNumber: 105
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 17
      RuleAction: allow
  IngressAllTrafficRestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock:
        Fn::ImportValue: dev-harbor-network-vpc-subnets-use1-VpcCidr
      Egress: false
      NetworkAclId:
        Ref: RestrictiveNacl
      PortRange:
        From: 0
        To: 65535
      Protocol: -1
      RuleAction: allow
      RuleNumber: 106
  EgressTcp80RestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 80
        To: 80
      RuleNumber: 100
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 6
      RuleAction: allow
  EgressTcp443RestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 443
        To: 443
      RuleNumber: 101
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 6
      RuleAction: allow
  EgressTcpEphemeralRestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 1024
        To: 65535
      RuleNumber: 102
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 6
      RuleAction: allow
  EgressTcpDnsRestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 53
        To: 53
      RuleNumber: 103
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 6
      RuleAction: allow
  EgressUdpDnsRestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 53
        To: 53
      RuleNumber: 104
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 17
      RuleAction: allow
  EgressUdpNtpRestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      PortRange:
        From: 123
        To: 123
      RuleNumber: 105
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: RestrictiveNacl
      Protocol: 17
      RuleAction: allow
  RestrictiveNacl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: Name
          Value: dev-harbor-network-nacls-use1-RestrictiveNacl
      VpcId:
        Fn::ImportValue: dev-harbor-network-vpc-subnets-use1-VpcId
  ApplicationsARestrictiveNaclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: RestrictiveNacl
      SubnetId:
        Fn::ImportValue: dev-harbor-network-vpc-subnets-use1-SubnetApplicationsAId
  ApplicationsBRestrictiveNaclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: RestrictiveNacl
      SubnetId:
        Fn::ImportValue: dev-harbor-network-vpc-subnets-use1-SubnetApplicationsBId
  PublicARestrictiveNaclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: RestrictiveNacl
      SubnetId:
        Fn::ImportValue: dev-harbor-network-vpc-subnets-use1-SubnetPublicAId
  EgressAllTrafficRestrictiveNaclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock:
        Fn::ImportValue: dev-harbor-network-vpc-subnets-use1-VpcCidr
      Egress: true
      NetworkAclId:
        Ref: RestrictiveNacl
      PortRange:
        From: 0
        To: 65535
      Protocol: -1
      RuleAction: allow
      RuleNumber: 106
  PublicBRestrictiveNaclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: RestrictiveNacl
      SubnetId:
        Fn::ImportValue: dev-harbor-network-vpc-subnets-use1-SubnetPublicBId
Outputs:
  RestrictiveNaclId:
    Value:
      Ref: RestrictiveNacl
    Export:
      Name: dev-harbor-network-nacls-use1-RestrictiveNaclId
