use serde_derive::{Deserialize, Serialize};

/// Module to generate the Detail report
pub mod detail;

/// Enum to specify the Analytic kind.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub enum AnalyticProviderKind {
    /// SBOM generated by Harbor.
    SbomDetail,
}