use std::fmt::{Display, Formatter};
use serde_derive::{Deserialize, Serialize};

/// Module to generate the Detail report
pub mod detail;

/// Enum to specify the Analytic kind.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub enum AnalyticProviderKind {
    /// SBOM generated by Harbor.
    SbomDetail,
}

impl Display for AnalyticProviderKind {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            AnalyticProviderKind::SbomDetail => write!(f, "sbom-detail"),
        }
    }
}