use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AffectsInner {
    #[serde(rename = "ref")]
    pub r#ref: String,
    /// Zero or more individual versions or range of versions.
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Vec<crate::entities::cyclonedx::VersionsInner>>,
}

impl AffectsInner {
    pub fn new(r#ref: String) -> AffectsInner {
        AffectsInner {
            r#ref,
            versions: None,
        }
    }
}
