use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

/// ComponentEvidence : Provides the ability to document evidence collected through various forms of extraction or analysis.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ComponentEvidence {
    #[serde(rename = "licenses", skip_serializing_if = "Option::is_none")]
    pub licenses: Option<Vec<crate::models::cyclonedx::LicenseChoice>>,
    #[serde(rename = "copyright", skip_serializing_if = "Option::is_none")]
    pub copyright: Option<Vec<crate::models::cyclonedx::Copyright>>,
}

impl ComponentEvidence {
    /// Provides the ability to document evidence collected through various forms of extraction or analysis.
    pub fn new() -> ComponentEvidence {
        ComponentEvidence {
            licenses: None,
            copyright: None,
        }
    }
}


