use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

/// ComponentPedigree : Component pedigree is a way to document complex supply chain scenarios where components are created, distributed, modified, redistributed, combined with other components, etc. Pedigree supports viewing this complex chain from the beginning, the end, or anywhere in the middle. It also provides a way to document variants where the exact relation may not be known.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ComponentPedigree {
    /// Describes zero or more components in which a component is derived from. This is commonly used to describe forks from existing projects where the forked version contains a ancestor node containing the original component it was forked from. For example, Component A is the original component. Component B is the component being used and documented in the BOM. However, Component B contains a pedigree node with a single ancestor documenting Component A - the original component from which Component B is derived from.
    #[serde(rename = "ancestors", skip_serializing_if = "Option::is_none")]
    pub ancestors: Option<Vec<crate::models::cyclonedx::Component>>,
    /// Descendants are the exact opposite of ancestors. This provides a way to document all forks (and their forks) of an original or root component.
    #[serde(rename = "descendants", skip_serializing_if = "Option::is_none")]
    pub descendants: Option<Vec<crate::models::cyclonedx::Component>>,
    /// Variants describe relations where the relationship between the components are not known. For example, if Component A contains nearly identical code to Component B. They are both related, but it is unclear if one is derived from the other, or if they share a common ancestor.
    #[serde(rename = "variants", skip_serializing_if = "Option::is_none")]
    pub variants: Option<Vec<crate::models::cyclonedx::Component>>,
    /// A list of zero or more commits which provide a trail describing how the component deviates from an ancestor, descendant, or variant.
    #[serde(rename = "commits", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Vec<crate::models::cyclonedx::Commit>>,
    /// >A list of zero or more patches describing how the component deviates from an ancestor, descendant, or variant. Patches may be complimentary to commits or may be used in place of commits.
    #[serde(rename = "patches", skip_serializing_if = "Option::is_none")]
    pub patches: Option<Vec<crate::models::cyclonedx::Patch>>,
    /// Notes, observations, and other non-structured commentary describing the components pedigree.
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl ComponentPedigree {
    /// Component pedigree is a way to document complex supply chain scenarios where components are created, distributed, modified, redistributed, combined with other components, etc. Pedigree supports viewing this complex chain from the beginning, the end, or anywhere in the middle. It also provides a way to document variants where the exact relation may not be known.
    pub fn new() -> ComponentPedigree {
        ComponentPedigree {
            ancestors: None,
            descendants: None,
            variants: None,
            commits: None,
            patches: None,
            notes: None,
        }
    }
}


