use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

/// Dependency : Defines the direct dependencies of a component. Components that do not have their own dependencies MUST be declared as empty elements within the graph. Components that are not represented in the dependency graph MAY have unknown dependencies. It is RECOMMENDED that implementations assume this to be opaque and not an indicator of a component being dependency-free.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dependency {
    #[serde(rename = "ref")]
    pub r#ref: String,
    /// The bom-ref identifiers of the components that are dependencies of this dependency object.
    #[serde(rename = "dependsOn", skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<String>>,
}

impl Dependency {
    /// Defines the direct dependencies of a component. Components that do not have their own dependencies MUST be declared as empty elements within the graph. Components that are not represented in the dependency graph MAY have unknown dependencies. It is RECOMMENDED that implementations assume this to be opaque and not an indicator of a component being dependency-free.
    pub fn new(r#ref: String) -> Dependency {
        Dependency {
            r#ref,
            depends_on: None,
        }
    }
}


