use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReferencesInner {
    /// An identifier that uniquely identifies the vulnerability.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "source")]
    pub source: Box<crate::entities::cyclonedx::models::VulnerabilitySource>,
}

impl ReferencesInner {
    pub fn new(
        id: String,
        source: crate::entities::cyclonedx::models::VulnerabilitySource,
    ) -> ReferencesInner {
        ReferencesInner {
            id,
            source: Box::new(source),
        }
    }
}
