use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

/// Specifies the severity or risk scoring methodology or standard used.  * CVSSv2 - [Common Vulnerability Scoring System v2](https://www.first.org/cvss/v2/) * CVSSv3 - [Common Vulnerability Scoring System v3](https://www.first.org/cvss/v3-0/) * CVSSv31 - [Common Vulnerability Scoring System v3.1](https://www.first.org/cvss/v3-1/) * OWASP - [OWASP Risk Rating Methodology](https://owasp.org/www-community/OWASP_Risk_Rating_Methodology)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScoreMethod {
    #[serde(rename = "CVSSv2")]
    Cvssv2,
    #[serde(rename = "CVSSv3")]
    Cvssv3,
    #[serde(rename = "CVSSv31")]
    Cvssv31,
    #[serde(rename = "OWASP")]
    Owasp,
    #[serde(rename = "other")]
    Other,
}

impl ToString for ScoreMethod {
    fn to_string(&self) -> String {
        match self {
            Self::Cvssv2 => String::from("CVSSv2"),
            Self::Cvssv3 => String::from("CVSSv3"),
            Self::Cvssv31 => String::from("CVSSv31"),
            Self::Owasp => String::from("OWASP"),
            Self::Other => String::from("other"),
        }
    }
}

impl Default for ScoreMethod {
    fn default() -> ScoreMethod {
        Self::Cvssv2
    }
}
