use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpdxPeriodSchema {
    #[serde(rename = "AFL-2.0")]
    Afl2Period0,
    #[serde(rename = "AAL")]
    Aal,
    #[serde(rename = "Adobe-2006")]
    Adobe2006,
    #[serde(rename = "AFL-3.0")]
    Afl3Period0,
    #[serde(rename = "ADSL")]
    Adsl,
    #[serde(rename = "0BSD")]
    Variant0Bsd,
    #[serde(rename = "Afmparse")]
    Afmparse,
    #[serde(rename = "AFL-1.2")]
    Afl1Period2,
    #[serde(rename = "AGPL-1.0-or-later")]
    Agpl1Period0OrLater,
    #[serde(rename = "AFL-2.1")]
    Afl2Period1,
    #[serde(rename = "AFL-1.1")]
    Afl1Period1,
    #[serde(rename = "AGPL-1.0")]
    Agpl1Period0,
    #[serde(rename = "Adobe-Glyph")]
    AdobeGlyph,
    #[serde(rename = "AMDPLPA")]
    Amdplpa,
    #[serde(rename = "Aladdin")]
    Aladdin,
    #[serde(rename = "ANTLR-PD")]
    AntlrPd,
    #[serde(rename = "AML")]
    Aml,
    #[serde(rename = "Apache-1.0")]
    Apache1Period0,
    #[serde(rename = "ANTLR-PD-fallback")]
    AntlrPdFallback,
    #[serde(rename = "Abstyles")]
    Abstyles,
    #[serde(rename = "AGPL-1.0-only")]
    Agpl1Period0Only,
    #[serde(rename = "APAFML")]
    Apafml,
    #[serde(rename = "APSL-1.0")]
    Apsl1Period0,
    #[serde(rename = "APSL-1.1")]
    Apsl1Period1,
    #[serde(rename = "APSL-2.0")]
    Apsl2Period0,
    #[serde(rename = "AGPL-3.0-only")]
    Agpl3Period0Only,
    #[serde(rename = "Apache-1.1")]
    Apache1Period1,
    #[serde(rename = "Apache-2.0")]
    Apache2Period0,
    #[serde(rename = "APL-1.0")]
    Apl1Period0,
    #[serde(rename = "Bahyph")]
    Bahyph,
    #[serde(rename = "Artistic-1.0")]
    Artistic1Period0,
    #[serde(rename = "AMPAS")]
    Ampas,
    #[serde(rename = "Barr")]
    Barr,
    #[serde(rename = "AGPL-3.0-or-later")]
    Agpl3Period0OrLater,
    #[serde(rename = "BlueOak-1.0.0")]
    BlueOak1Period0Period0,
    #[serde(rename = "Beerware")]
    Beerware,
    #[serde(rename = "Artistic-1.0-cl8")]
    Artistic1Period0Cl8,
    #[serde(rename = "blessing")]
    Blessing,
    #[serde(rename = "Borceux")]
    Borceux,
    #[serde(rename = "BSD-2-Clause-NetBSD")]
    Bsd2ClauseNetBsd,
    #[serde(rename = "BSD-1-Clause")]
    Bsd1Clause,
    #[serde(rename = "BSD-2-Clause-Patent")]
    Bsd2ClausePatent,
    #[serde(rename = "BitTorrent-1.0")]
    BitTorrent1Period0,
    #[serde(rename = "BSD-2-Clause-FreeBSD")]
    Bsd2ClauseFreeBsd,
    #[serde(rename = "BSD-3-Clause-Attribution")]
    Bsd3ClauseAttribution,
    #[serde(rename = "BSD-2-Clause")]
    Bsd2Clause,
    #[serde(rename = "APSL-1.2")]
    Apsl1Period2,
    #[serde(rename = "BSD-3-Clause-LBNL")]
    Bsd3ClauseLbnl,
    #[serde(rename = "Artistic-2.0")]
    Artistic2Period0,
    #[serde(rename = "BSD-3-Clause-No-Nuclear-License-2014")]
    Bsd3ClauseNoNuclearLicense2014,
    #[serde(rename = "BSD-3-Clause-Modification")]
    Bsd3ClauseModification,
    #[serde(rename = "BSD-4-Clause-Shortened")]
    Bsd4ClauseShortened,
    #[serde(rename = "BSD-3-Clause")]
    Bsd3Clause,
    #[serde(rename = "BSD-3-Clause-Open-MPI")]
    Bsd3ClauseOpenMpi,
    #[serde(rename = "BitTorrent-1.1")]
    BitTorrent1Period1,
    #[serde(rename = "BSD-3-Clause-No-Nuclear-Warranty")]
    Bsd3ClauseNoNuclearWarranty,
    #[serde(rename = "BSD-Source-Code")]
    BsdSourceCode,
    #[serde(rename = "BSD-Protection")]
    BsdProtection,
    #[serde(rename = "AGPL-3.0")]
    Agpl3Period0,
    #[serde(rename = "BUSL-1.1")]
    Busl1Period1,
    #[serde(rename = "Artistic-1.0-Perl")]
    Artistic1Period0Perl,
    #[serde(rename = "BSL-1.0")]
    Bsl1Period0,
    #[serde(rename = "BSD-2-Clause-Views")]
    Bsd2ClauseViews,
    #[serde(rename = "CAL-1.0-Combined-Work-Exception")]
    Cal1Period0CombinedWorkException,
    #[serde(rename = "CATOSL-1.1")]
    Catosl1Period1,
    #[serde(rename = "bzip2-1.0.5")]
    Bzip21Period0Period5,
    #[serde(rename = "bzip2-1.0.6")]
    Bzip21Period0Period6,
    #[serde(rename = "CC-BY-2.5")]
    CcBy2Period5,
    #[serde(rename = "CC-BY-3.0-AT")]
    CcBy3Period0At,
    #[serde(rename = "C-UDA-1.0")]
    CUda1Period0,
    #[serde(rename = "CC-BY-3.0-US")]
    CcBy3Period0Us,
    #[serde(rename = "CC-BY-1.0")]
    CcBy1Period0,
    #[serde(rename = "CC-BY-NC-1.0")]
    CcByNc1Period0,
    #[serde(rename = "CC-BY-NC-2.0")]
    CcByNc2Period0,
    #[serde(rename = "CC-BY-NC-2.5")]
    CcByNc2Period5,
    #[serde(rename = "CC-BY-2.0")]
    CcBy2Period0,
    #[serde(rename = "CC-BY-NC-4.0")]
    CcByNc4Period0,
    #[serde(rename = "CC-BY-NC-ND-1.0")]
    CcByNcNd1Period0,
    #[serde(rename = "CC-BY-NC-ND-2.0")]
    CcByNcNd2Period0,
    #[serde(rename = "CC-BY-NC-3.0")]
    CcByNc3Period0,
    #[serde(rename = "CC-BY-NC-ND-3.0-IGO")]
    CcByNcNd3Period0Igo,
    #[serde(rename = "CC-BY-NC-ND-3.0")]
    CcByNcNd3Period0,
    #[serde(rename = "BSD-3-Clause-No-Nuclear-License")]
    Bsd3ClauseNoNuclearLicense,
    #[serde(rename = "CC-BY-NC-ND-4.0")]
    CcByNcNd4Period0,
    #[serde(rename = "CC-BY-NC-SA-2.0")]
    CcByNcSa2Period0,
    #[serde(rename = "CC-BY-NC-SA-2.5")]
    CcByNcSa2Period5,
    #[serde(rename = "CC-BY-NC-SA-3.0")]
    CcByNcSa3Period0,
    #[serde(rename = "CC-BY-NC-SA-4.0")]
    CcByNcSa4Period0,
    #[serde(rename = "CC-BY-ND-1.0")]
    CcByNd1Period0,
    #[serde(rename = "BSD-3-Clause-Clear")]
    Bsd3ClauseClear,
    #[serde(rename = "CC-BY-ND-2.5")]
    CcByNd2Period5,
    #[serde(rename = "CC-BY-ND-3.0")]
    CcByNd3Period0,
    #[serde(rename = "CC-BY-ND-4.0")]
    CcByNd4Period0,
    #[serde(rename = "CC-BY-SA-1.0")]
    CcBySa1Period0,
    #[serde(rename = "CC-BY-SA-2.0-UK")]
    CcBySa2Period0Uk,
    #[serde(rename = "CC-BY-SA-2.0")]
    CcBySa2Period0,
    #[serde(rename = "CC-BY-SA-2.1-JP")]
    CcBySa2Period1Jp,
    #[serde(rename = "CC-BY-ND-2.0")]
    CcByNd2Period0,
    #[serde(rename = "CC-BY-SA-3.0-AT")]
    CcBySa3Period0At,
    #[serde(rename = "CC-BY-SA-3.0")]
    CcBySa3Period0,
    #[serde(rename = "CC-BY-SA-4.0")]
    CcBySa4Period0,
    #[serde(rename = "CC-BY-SA-2.5")]
    CcBySa2Period5,
    #[serde(rename = "CC-BY-3.0")]
    CcBy3Period0,
    #[serde(rename = "CDDL-1.0")]
    Cddl1Period0,
    #[serde(rename = "CC0-1.0")]
    Cc01Period0,
    #[serde(rename = "CC-BY-NC-ND-2.5")]
    CcByNcNd2Period5,
    #[serde(rename = "CC-BY-NC-SA-1.0")]
    CcByNcSa1Period0,
    #[serde(rename = "Caldera")]
    Caldera,
    #[serde(rename = "CDLA-Permissive-1.0")]
    CdlaPermissive1Period0,
    #[serde(rename = "CC-BY-4.0")]
    CcBy4Period0,
    #[serde(rename = "CC-PDDC")]
    CcPddc,
    #[serde(rename = "BSD-4-Clause-UC")]
    Bsd4ClauseUc,
    #[serde(rename = "BSD-4-Clause")]
    Bsd4Clause,
    #[serde(rename = "CAL-1.0")]
    Cal1Period0,
    #[serde(rename = "CDDL-1.1")]
    Cddl1Period1,
    #[serde(rename = "CERN-OHL-1.2")]
    CernOhl1Period2,
    #[serde(rename = "CERN-OHL-1.1")]
    CernOhl1Period1,
    #[serde(rename = "CERN-OHL-P-2.0")]
    CernOhlP2Period0,
    #[serde(rename = "CERN-OHL-S-2.0")]
    CernOhlS2Period0,
    #[serde(rename = "CECILL-1.1")]
    Cecill1Period1,
    #[serde(rename = "CECILL-2.0")]
    Cecill2Period0,
    #[serde(rename = "CECILL-1.0")]
    Cecill1Period0,
    #[serde(rename = "CNRI-Python")]
    CnriPython,
    #[serde(rename = "CNRI-Python-GPL-Compatible")]
    CnriPythonGplCompatible,
    #[serde(rename = "copyleft-next-0.3.0")]
    CopyleftNext0Period3Period0,
    #[serde(rename = "CPAL-1.0")]
    Cpal1Period0,
    #[serde(rename = "copyleft-next-0.3.1")]
    CopyleftNext0Period3Period1,
    #[serde(rename = "CPL-1.0")]
    Cpl1Period0,
    #[serde(rename = "ClArtistic")]
    ClArtistic,
    #[serde(rename = "CECILL-C")]
    CecillC,
    #[serde(rename = "CNRI-Jython")]
    CnriJython,
    #[serde(rename = "Condor-1.1")]
    Condor1Period1,
    #[serde(rename = "CPOL-1.02")]
    Cpol1Period02,
    #[serde(rename = "curl")]
    Curl,
    #[serde(rename = "diffmark")]
    Diffmark,
    #[serde(rename = "Crossword")]
    Crossword,
    #[serde(rename = "Dotseqn")]
    Dotseqn,
    #[serde(rename = "DOC")]
    Doc,
    #[serde(rename = "DSDP")]
    Dsdp,
    #[serde(rename = "DRL-1.0")]
    Drl1Period0,
    #[serde(rename = "ECL-1.0")]
    Ecl1Period0,
    #[serde(rename = "ECL-2.0")]
    Ecl2Period0,
    #[serde(rename = "eCos-2.0")]
    ECos2Period0,
    #[serde(rename = "CrystalStacker")]
    CrystalStacker,
    #[serde(rename = "CERN-OHL-W-2.0")]
    CernOhlW2Period0,
    #[serde(rename = "D-FSL-1.0")]
    DFsl1Period0,
    #[serde(rename = "eGenix")]
    EGenix,
    #[serde(rename = "EPICS")]
    Epics,
    #[serde(rename = "Entessa")]
    Entessa,
    #[serde(rename = "EPL-1.0")]
    Epl1Period0,
    #[serde(rename = "EFL-2.0")]
    Efl2Period0,
    #[serde(rename = "CUA-OPL-1.0")]
    CuaOpl1Period0,
    #[serde(rename = "etalab-2.0")]
    Etalab2Period0,
    #[serde(rename = "EUPL-1.0")]
    Eupl1Period0,
    #[serde(rename = "ErlPL-1.1")]
    ErlPl1Period1,
    #[serde(rename = "EUDatagrid")]
    EuDatagrid,
    #[serde(rename = "EUPL-1.1")]
    Eupl1Period1,
    #[serde(rename = "Cube")]
    Cube,
    #[serde(rename = "dvipdfm")]
    Dvipdfm,
    #[serde(rename = "FreeBSD-DOC")]
    FreeBsdDoc,
    #[serde(rename = "Eurosym")]
    Eurosym,
    #[serde(rename = "FSFAP")]
    Fsfap,
    #[serde(rename = "FreeImage")]
    FreeImage,
    #[serde(rename = "FSFULLR")]
    Fsfullr,
    #[serde(rename = "FSFUL")]
    Fsful,
    #[serde(rename = "GD")]
    Gd,
    #[serde(rename = "GFDL-1.1-invariants-only")]
    Gfdl1Period1InvariantsOnly,
    #[serde(rename = "EUPL-1.2")]
    Eupl1Period2,
    #[serde(rename = "EPL-2.0")]
    Epl2Period0,
    #[serde(rename = "GFDL-1.1-no-invariants-or-later")]
    Gfdl1Period1NoInvariantsOrLater,
    #[serde(rename = "GFDL-1.1-only")]
    Gfdl1Period1Only,
    #[serde(rename = "GFDL-1.1-or-later")]
    Gfdl1Period1OrLater,
    #[serde(rename = "GFDL-1.1")]
    Gfdl1Period1,
    #[serde(rename = "FTL")]
    Ftl,
    #[serde(rename = "GFDL-1.2-invariants-or-later")]
    Gfdl1Period2InvariantsOrLater,
    #[serde(rename = "GFDL-1.1-invariants-or-later")]
    Gfdl1Period1InvariantsOrLater,
    #[serde(rename = "GFDL-1.2-invariants-only")]
    Gfdl1Period2InvariantsOnly,
    #[serde(rename = "GFDL-1.2-only")]
    Gfdl1Period2Only,
    #[serde(rename = "GFDL-1.2-or-later")]
    Gfdl1Period2OrLater,
    #[serde(rename = "GFDL-1.2")]
    Gfdl1Period2,
    #[serde(rename = "GFDL-1.2-no-invariants-only")]
    Gfdl1Period2NoInvariantsOnly,
    #[serde(rename = "GFDL-1.3-invariants-only")]
    Gfdl1Period3InvariantsOnly,
    #[serde(rename = "GFDL-1.3-no-invariants-only")]
    Gfdl1Period3NoInvariantsOnly,
    #[serde(rename = "GFDL-1.3-invariants-or-later")]
    Gfdl1Period3InvariantsOrLater,
    #[serde(rename = "GFDL-1.2-no-invariants-or-later")]
    Gfdl1Period2NoInvariantsOrLater,
    #[serde(rename = "Fair")]
    Fair,
    #[serde(rename = "Frameworx-1.0")]
    Frameworx1Period0,
    #[serde(rename = "Giftware")]
    Giftware,
    #[serde(rename = "GFDL-1.1-no-invariants-only")]
    Gfdl1Period1NoInvariantsOnly,
    #[serde(rename = "GL2PS")]
    Gl2Ps,
    #[serde(rename = "Glulxe")]
    Glulxe,
    #[serde(rename = "Glide")]
    Glide,
    #[serde(rename = "gnuplot")]
    Gnuplot,
    #[serde(rename = "GLWTPL")]
    Glwtpl,
    #[serde(rename = "GPL-1.0-only")]
    Gpl1Period0Only,
    #[serde(rename = "GPL-1.0-or-later")]
    Gpl1Period0OrLater,
    #[serde(rename = "GPL-1.0")]
    Gpl1Period0,
    #[serde(rename = "GFDL-1.3-only")]
    Gfdl1Period3Only,
    #[serde(rename = "GPL-2.0-only")]
    Gpl2Period0Only,
    #[serde(rename = "GPL-2.0-or-later")]
    Gpl2Period0OrLater,
    #[serde(rename = "GPL-2.0-with-autoconf-exception")]
    Gpl2Period0WithAutoconfException,
    #[serde(rename = "GPL-2.0+")]
    Gpl2Period0Plus,
    #[serde(rename = "GFDL-1.3")]
    Gfdl1Period3,
    #[serde(rename = "GPL-1.0+")]
    Gpl1Period0Plus,
    #[serde(rename = "CDLA-Sharing-1.0")]
    CdlaSharing1Period0,
    #[serde(rename = "GPL-2.0-with-classpath-exception")]
    Gpl2Period0WithClasspathException,
    #[serde(rename = "GPL-2.0-with-GCC-exception")]
    Gpl2Period0WithGccException,
    #[serde(rename = "GPL-2.0-with-bison-exception")]
    Gpl2Period0WithBisonException,
    #[serde(rename = "GPL-2.0-with-font-exception")]
    Gpl2Period0WithFontException,
    #[serde(rename = "GPL-2.0")]
    Gpl2Period0,
    #[serde(rename = "CECILL-2.1")]
    Cecill2Period1,
    #[serde(rename = "GPL-3.0")]
    Gpl3Period0,
    #[serde(rename = "GPL-3.0+")]
    Gpl3Period0Plus,
    #[serde(rename = "GPL-3.0-with-autoconf-exception")]
    Gpl3Period0WithAutoconfException,
    #[serde(rename = "GPL-3.0-only")]
    Gpl3Period0Only,
    #[serde(rename = "Hippocratic-2.1")]
    Hippocratic2Period1,
    #[serde(rename = "HPND")]
    Hpnd,
    #[serde(rename = "HTMLTIDY")]
    Htmltidy,
    #[serde(rename = "GPL-3.0-with-GCC-exception")]
    Gpl3Period0WithGccException,
    #[serde(rename = "HaskellReport")]
    HaskellReport,
    #[serde(rename = "GPL-3.0-or-later")]
    Gpl3Period0OrLater,
    #[serde(rename = "ICU")]
    Icu,
    #[serde(rename = "ImageMagick")]
    ImageMagick,
    #[serde(rename = "iMatix")]
    IMatix,
    #[serde(rename = "IBM-pibs")]
    IbmPibs,
    #[serde(rename = "Intel-ACPI")]
    IntelAcpi,
    #[serde(rename = "Intel")]
    Intel,
    #[serde(rename = "Info-ZIP")]
    InfoZip,
    #[serde(rename = "IPA")]
    Ipa,
    #[serde(rename = "IJG")]
    Ijg,
    #[serde(rename = "ISC")]
    Isc,
    #[serde(rename = "JasPer-2.0")]
    JasPer2Period0,
    #[serde(rename = "JPNIC")]
    Jpnic,
    #[serde(rename = "JSON")]
    Json,
    #[serde(rename = "LAL-1.2")]
    Lal1Period2,
    #[serde(rename = "LAL-1.3")]
    Lal1Period3,
    #[serde(rename = "Latex2e")]
    Latex2e,
    #[serde(rename = "Leptonica")]
    Leptonica,
    #[serde(rename = "HPND-sell-variant")]
    HpndSellVariant,
    #[serde(rename = "LGPL-2.0-only")]
    Lgpl2Period0Only,
    #[serde(rename = "LGPL-2.0-or-later")]
    Lgpl2Period0OrLater,
    #[serde(rename = "Imlib2")]
    Imlib2,
    #[serde(rename = "IPL-1.0")]
    Ipl1Period0,
    #[serde(rename = "LGPL-2.1-only")]
    Lgpl2Period1Only,
    #[serde(rename = "LGPL-2.1-or-later")]
    Lgpl2Period1OrLater,
    #[serde(rename = "LGPL-2.0+")]
    Lgpl2Period0Plus,
    #[serde(rename = "LGPL-2.0")]
    Lgpl2Period0,
    #[serde(rename = "CECILL-B")]
    CecillB,
    #[serde(rename = "LGPL-3.0-or-later")]
    Lgpl3Period0OrLater,
    #[serde(rename = "LGPL-3.0-only")]
    Lgpl3Period0Only,
    #[serde(rename = "LGPLLR")]
    Lgpllr,
    #[serde(rename = "libpng-2.0")]
    Libpng2Period0,
    #[serde(rename = "Libpng")]
    Libpng,
    #[serde(rename = "libselinux-1.0")]
    Libselinux1Period0,
    #[serde(rename = "LGPL-3.0+")]
    Lgpl3Period0Plus,
    #[serde(rename = "EFL-1.0")]
    Efl1Period0,
    #[serde(rename = "libtiff")]
    Libtiff,
    #[serde(rename = "GFDL-1.3-no-invariants-or-later")]
    Gfdl1Period3NoInvariantsOrLater,
    #[serde(rename = "LiLiQ-Rplus-1.1")]
    LiLiQRplus1Period1,
    #[serde(rename = "LiLiQ-R-1.1")]
    LiLiQR1Period1,
    #[serde(rename = "LPL-1.0")]
    Lpl1Period0,
    #[serde(rename = "LiLiQ-P-1.1")]
    LiLiQP1Period1,
    #[serde(rename = "Linux-OpenIB")]
    LinuxOpenIb,
    #[serde(rename = "LPPL-1.0")]
    Lppl1Period0,
    #[serde(rename = "LPPL-1.2")]
    Lppl1Period2,
    #[serde(rename = "LPPL-1.3a")]
    Lppl1Period3a,
    #[serde(rename = "LPL-1.02")]
    Lpl1Period02,
    #[serde(rename = "LPPL-1.3c")]
    Lppl1Period3c,
    #[serde(rename = "MakeIndex")]
    MakeIndex,
    #[serde(rename = "LGPL-2.1+")]
    Lgpl2Period1Plus,
    #[serde(rename = "LPPL-1.1")]
    Lppl1Period1,
    #[serde(rename = "MIT-CMU")]
    MitCmu,
    #[serde(rename = "MirOS")]
    MirOs,
    #[serde(rename = "MIT-advertising")]
    MitAdvertising,
    #[serde(rename = "MIT-Modern-Variant")]
    MitModernVariant,
    #[serde(rename = "MIT")]
    Mit,
    #[serde(rename = "MIT-enna")]
    MitEnna,
    #[serde(rename = "MIT-open-group")]
    MitOpenGroup,
    #[serde(rename = "MIT-feh")]
    MitFeh,
    #[serde(rename = "MITNFA")]
    Mitnfa,
    #[serde(rename = "MPL-1.0")]
    Mpl1Period0,
    #[serde(rename = "mpich2")]
    Mpich2,
    #[serde(rename = "MPL-2.0")]
    Mpl2Period0,
    #[serde(rename = "MPL-2.0-no-copyleft-exception")]
    Mpl2Period0NoCopyleftException,
    #[serde(rename = "MS-RL")]
    MsRl,
    #[serde(rename = "MTLL")]
    Mtll,
    #[serde(rename = "MPL-1.1")]
    Mpl1Period1,
    #[serde(rename = "MulanPSL-2.0")]
    MulanPsl2Period0,
    #[serde(rename = "Motosoto")]
    Motosoto,
    #[serde(rename = "Mup")]
    Mup,
    #[serde(rename = "MulanPSL-1.0")]
    MulanPsl1Period0,
    #[serde(rename = "NAIST-2003")]
    Naist2003,
    #[serde(rename = "Naumen")]
    Naumen,
    #[serde(rename = "Multics")]
    Multics,
    #[serde(rename = "NBPL-1.0")]
    Nbpl1Period0,
    #[serde(rename = "NCSA")]
    Ncsa,
    #[serde(rename = "Net-SNMP")]
    NetSnmp,
    #[serde(rename = "NetCDF")]
    NetCdf,
    #[serde(rename = "NASA-1.3")]
    Nasa1Period3,
    #[serde(rename = "NGPL")]
    Ngpl,
    #[serde(rename = "NIST-PD-fallback")]
    NistPdFallback,
    #[serde(rename = "NIST-PD")]
    NistPd,
    #[serde(rename = "Newsletr")]
    Newsletr,
    #[serde(rename = "NLPL")]
    Nlpl,
    #[serde(rename = "Nokia")]
    Nokia,
    #[serde(rename = "NOSL")]
    Nosl,
    #[serde(rename = "Noweb")]
    Noweb,
    #[serde(rename = "NLOD-1.0")]
    Nlod1Period0,
    #[serde(rename = "NPL-1.0")]
    Npl1Period0,
    #[serde(rename = "NCGL-UK-2.0")]
    NcglUk2Period0,
    #[serde(rename = "NRL")]
    Nrl,
    #[serde(rename = "NTP-0")]
    Ntp0,
    #[serde(rename = "NTP")]
    Ntp,
    #[serde(rename = "GFDL-1.3-or-later")]
    Gfdl1Period3OrLater,
    #[serde(rename = "Nunit")]
    Nunit,
    #[serde(rename = "O-UDA-1.0")]
    OUda1Period0,
    #[serde(rename = "NPL-1.1")]
    Npl1Period1,
    #[serde(rename = "OCCT-PL")]
    OcctPl,
    #[serde(rename = "ODC-By-1.0")]
    OdcBy1Period0,
    #[serde(rename = "OFL-1.0-no-RFN")]
    Ofl1Period0NoRfn,
    #[serde(rename = "OCLC-2.0")]
    Oclc2Period0,
    #[serde(rename = "OFL-1.0-RFN")]
    Ofl1Period0Rfn,
    #[serde(rename = "OFL-1.0")]
    Ofl1Period0,
    #[serde(rename = "OFL-1.1-no-RFN")]
    Ofl1Period1NoRfn,
    #[serde(rename = "OFL-1.1-RFN")]
    Ofl1Period1Rfn,
    #[serde(rename = "OFL-1.1")]
    Ofl1Period1,
    #[serde(rename = "OGDL-Taiwan-1.0")]
    OgdlTaiwan1Period0,
    #[serde(rename = "OGC-1.0")]
    Ogc1Period0,
    #[serde(rename = "OGL-UK-1.0")]
    OglUk1Period0,
    #[serde(rename = "OGL-UK-2.0")]
    OglUk2Period0,
    #[serde(rename = "OGL-UK-3.0")]
    OglUk3Period0,
    #[serde(rename = "OGTSL")]
    Ogtsl,
    #[serde(rename = "OLDAP-1.1")]
    Oldap1Period1,
    #[serde(rename = "OLDAP-1.2")]
    Oldap1Period2,
    #[serde(rename = "OLDAP-1.3")]
    Oldap1Period3,
    #[serde(rename = "OGL-Canada-2.0")]
    OglCanada2Period0,
    #[serde(rename = "OLDAP-2.0.1")]
    Oldap2Period0Period1,
    #[serde(rename = "OLDAP-2.0")]
    Oldap2Period0,
    #[serde(rename = "OLDAP-2.1")]
    Oldap2Period1,
    #[serde(rename = "OLDAP-2.2.1")]
    Oldap2Period2Period1,
    #[serde(rename = "OLDAP-2.2.2")]
    Oldap2Period2Period2,
    #[serde(rename = "OLDAP-2.2")]
    Oldap2Period2,
    #[serde(rename = "ODbL-1.0")]
    OdbL1Period0,
    #[serde(rename = "OLDAP-2.4")]
    Oldap2Period4,
    #[serde(rename = "OLDAP-1.4")]
    Oldap1Period4,
    #[serde(rename = "OLDAP-2.3")]
    Oldap2Period3,
    #[serde(rename = "OLDAP-2.7")]
    Oldap2Period7,
    #[serde(rename = "OLDAP-2.8")]
    Oldap2Period8,
    #[serde(rename = "OML")]
    Oml,
    #[serde(rename = "OpenSSL")]
    OpenSsl,
    #[serde(rename = "OLDAP-2.6")]
    Oldap2Period6,
    #[serde(rename = "OPL-1.0")]
    Opl1Period0,
    #[serde(rename = "OSL-1.0")]
    Osl1Period0,
    #[serde(rename = "OSL-1.1")]
    Osl1Period1,
    #[serde(rename = "OSL-2.0")]
    Osl2Period0,
    #[serde(rename = "OSET-PL-2.1")]
    OsetPl2Period1,
    #[serde(rename = "OSL-2.1")]
    Osl2Period1,
    #[serde(rename = "Parity-6.0.0")]
    Parity6Period0Period0,
    #[serde(rename = "Parity-7.0.0")]
    Parity7Period0Period0,
    #[serde(rename = "PDDL-1.0")]
    Pddl1Period0,
    #[serde(rename = "PHP-3.0")]
    Php3Period0,
    #[serde(rename = "OSL-3.0")]
    Osl3Period0,
    #[serde(rename = "Plexus")]
    Plexus,
    #[serde(rename = "MS-PL")]
    MsPl,
    #[serde(rename = "PolyForm-Small-Business-1.0.0")]
    PolyFormSmallBusiness1Period0Period0,
    #[serde(rename = "PolyForm-Noncommercial-1.0.0")]
    PolyFormNoncommercial1Period0Period0,
    #[serde(rename = "PSF-2.0")]
    Psf2Period0,
    #[serde(rename = "psfrag")]
    Psfrag,
    #[serde(rename = "PostgreSQL")]
    PostgreSql,
    #[serde(rename = "psutils")]
    Psutils,
    #[serde(rename = "Qhull")]
    Qhull,
    #[serde(rename = "QPL-1.0")]
    Qpl1Period0,
    #[serde(rename = "Rdisc")]
    Rdisc,
    #[serde(rename = "Python-2.0")]
    Python2Period0,
    #[serde(rename = "RPL-1.1")]
    Rpl1Period1,
    #[serde(rename = "RPL-1.5")]
    Rpl1Period5,
    #[serde(rename = "RHeCos-1.1")]
    RheCos1Period1,
    #[serde(rename = "RSA-MD")]
    RsaMd,
    #[serde(rename = "RSCPL")]
    Rscpl,
    #[serde(rename = "Ruby")]
    Ruby,
    #[serde(rename = "SAX-PD")]
    SaxPd,
    #[serde(rename = "Saxpath")]
    Saxpath,
    #[serde(rename = "SCEA")]
    Scea,
    #[serde(rename = "Sendmail-8.23")]
    Sendmail8Period23,
    #[serde(rename = "Sendmail")]
    Sendmail,
    #[serde(rename = "SGI-B-1.0")]
    SgiB1Period0,
    #[serde(rename = "SGI-B-1.1")]
    SgiB1Period1,
    #[serde(rename = "SGI-B-2.0")]
    SgiB2Period0,
    #[serde(rename = "SHL-0.5")]
    Shl0Period5,
    #[serde(rename = "SHL-0.51")]
    Shl0Period51,
    #[serde(rename = "SimPL-2.0")]
    SimPl2Period0,
    #[serde(rename = "SISSL-1.2")]
    Sissl1Period2,
    #[serde(rename = "SISSL")]
    Sissl,
    #[serde(rename = "Sleepycat")]
    Sleepycat,
    #[serde(rename = "SMLNJ")]
    Smlnj,
    #[serde(rename = "SMPPL")]
    Smppl,
    #[serde(rename = "SNIA")]
    Snia,
    #[serde(rename = "Spencer-86")]
    Spencer86,
    #[serde(rename = "Spencer-94")]
    Spencer94,
    #[serde(rename = "Spencer-99")]
    Spencer99,
    #[serde(rename = "SPL-1.0")]
    Spl1Period0,
    #[serde(rename = "SSH-OpenSSH")]
    SshOpenSsh,
    #[serde(rename = "PHP-3.01")]
    Php3Period01,
    #[serde(rename = "SSH-short")]
    SshShort,
    #[serde(rename = "MIT-0")]
    Mit0,
    #[serde(rename = "RPSL-1.0")]
    Rpsl1Period0,
    #[serde(rename = "SWL")]
    Swl,
    #[serde(rename = "SugarCRM-1.1.3")]
    SugarCrm1Period1Period3,
    #[serde(rename = "TCL")]
    Tcl,
    #[serde(rename = "TCP-wrappers")]
    TcpWrappers,
    #[serde(rename = "SSPL-1.0")]
    Sspl1Period0,
    #[serde(rename = "TMate")]
    TMate,
    #[serde(rename = "TOSL")]
    Tosl,
    #[serde(rename = "TORQUE-1.1")]
    Torque1Period1,
    #[serde(rename = "TAPR-OHL-1.0")]
    TaprOhl1Period0,
    #[serde(rename = "UCL-1.0")]
    Ucl1Period0,
    #[serde(rename = "Unicode-DFS-2015")]
    UnicodeDfs2015,
    #[serde(rename = "Unicode-DFS-2016")]
    UnicodeDfs2016,
    #[serde(rename = "Unicode-TOU")]
    UnicodeTou,
    #[serde(rename = "TU-Berlin-1.0")]
    TuBerlin1Period0,
    #[serde(rename = "UPL-1.0")]
    Upl1Period0,
    #[serde(rename = "Unlicense")]
    Unlicense,
    #[serde(rename = "VOSTROM")]
    Vostrom,
    #[serde(rename = "Vim")]
    Vim,
    #[serde(rename = "VSL-1.0")]
    Vsl1Period0,
    #[serde(rename = "W3C-20150513")]
    W3C20150513,
    #[serde(rename = "W3C")]
    W3C,
    #[serde(rename = "W3C-19980720")]
    W3C19980720,
    #[serde(rename = "Wsuipa")]
    Wsuipa,
    #[serde(rename = "Watcom-1.0")]
    Watcom1Period0,
    #[serde(rename = "WTFPL")]
    Wtfpl,
    #[serde(rename = "X11")]
    X11,
    #[serde(rename = "Xerox")]
    Xerox,
    #[serde(rename = "XFree86-1.1")]
    XFree861Period1,
    #[serde(rename = "xinetd")]
    Xinetd,
    #[serde(rename = "Xnet")]
    Xnet,
    #[serde(rename = "xpp")]
    Xpp,
    #[serde(rename = "XSkat")]
    XSkat,
    #[serde(rename = "YPL-1.0")]
    Ypl1Period0,
    #[serde(rename = "YPL-1.1")]
    Ypl1Period1,
    #[serde(rename = "Zed")]
    Zed,
    #[serde(rename = "Zend-2.0")]
    Zend2Period0,
    #[serde(rename = "TU-Berlin-2.0")]
    TuBerlin2Period0,
    #[serde(rename = "Zimbra-1.4")]
    Zimbra1Period4,
    #[serde(rename = "zlib-acknowledgement")]
    ZlibAcknowledgement,
    #[serde(rename = "Zlib")]
    Zlib,
    #[serde(rename = "ZPL-1.1")]
    Zpl1Period1,
    #[serde(rename = "ZPL-2.0")]
    Zpl2Period0,
    #[serde(rename = "ZPL-2.1")]
    Zpl2Period1,
    #[serde(rename = "wxWindows")]
    WxWindows,
    #[serde(rename = "Zimbra-1.3")]
    Zimbra1Period3,
    #[serde(rename = "gSOAP-1.3b")]
    GSoap1Period3b,
    #[serde(rename = "Interbase-1.0")]
    Interbase1Period0,
    #[serde(rename = "LGPL-2.1")]
    Lgpl2Period1,
    #[serde(rename = "LGPL-3.0")]
    Lgpl3Period0,
    #[serde(rename = "NPOSL-3.0")]
    Nposl3Period0,
    #[serde(rename = "OLDAP-2.5")]
    Oldap2Period5,
    #[serde(rename = "StandardML-NJ")]
    StandardMlNj,
    #[serde(rename = "389-exception")]
    Variant389Exception,
    #[serde(rename = "Autoconf-exception-2.0")]
    AutoconfException2Period0,
    #[serde(rename = "Autoconf-exception-3.0")]
    AutoconfException3Period0,
    #[serde(rename = "Bison-exception-2.2")]
    BisonException2Period2,
    #[serde(rename = "Bootloader-exception")]
    BootloaderException,
    #[serde(rename = "Classpath-exception-2.0")]
    ClasspathException2Period0,
    #[serde(rename = "CLISP-exception-2.0")]
    ClispException2Period0,
    #[serde(rename = "DigiRule-FOSS-exception")]
    DigiRuleFossException,
    #[serde(rename = "eCos-exception-2.0")]
    ECosException2Period0,
    #[serde(rename = "Fawkes-Runtime-exception")]
    FawkesRuntimeException,
    #[serde(rename = "FLTK-exception")]
    FltkException,
    #[serde(rename = "Font-exception-2.0")]
    FontException2Period0,
    #[serde(rename = "freertos-exception-2.0")]
    FreertosException2Period0,
    #[serde(rename = "GCC-exception-2.0")]
    GccException2Period0,
    #[serde(rename = "GCC-exception-3.1")]
    GccException3Period1,
    #[serde(rename = "gnu-javamail-exception")]
    GnuJavamailException,
    #[serde(rename = "GPL-3.0-linking-exception")]
    Gpl3Period0LinkingException,
    #[serde(rename = "GPL-3.0-linking-source-exception")]
    Gpl3Period0LinkingSourceException,
    #[serde(rename = "GPL-CC-1.0")]
    GplCc1Period0,
    #[serde(rename = "i2p-gpl-java-exception")]
    I2pGplJavaException,
    #[serde(rename = "LGPL-3.0-linking-exception")]
    Lgpl3Period0LinkingException,
    #[serde(rename = "Libtool-exception")]
    LibtoolException,
    #[serde(rename = "Linux-syscall-note")]
    LinuxSyscallNote,
    #[serde(rename = "LLVM-exception")]
    LlvmException,
    #[serde(rename = "LZMA-exception")]
    LzmaException,
    #[serde(rename = "mif-exception")]
    MifException,
    #[serde(rename = "Nokia-Qt-exception-1.1")]
    NokiaQtException1Period1,
    #[serde(rename = "OCaml-LGPL-linking-exception")]
    OCamlLgplLinkingException,
    #[serde(rename = "OCCT-exception-1.0")]
    OcctException1Period0,
    #[serde(rename = "OpenJDK-assembly-exception-1.0")]
    OpenJdkAssemblyException1Period0,
    #[serde(rename = "openvpn-openssl-exception")]
    OpenvpnOpensslException,
    #[serde(rename = "PS-or-PDF-font-exception-20170817")]
    PsOrPdfFontException20170817,
    #[serde(rename = "Qt-GPL-exception-1.0")]
    QtGplException1Period0,
    #[serde(rename = "Qt-LGPL-exception-1.1")]
    QtLgplException1Period1,
    #[serde(rename = "Qwt-exception-1.0")]
    QwtException1Period0,
    #[serde(rename = "SHL-2.0")]
    Shl2Period0,
    #[serde(rename = "SHL-2.1")]
    Shl2Period1,
    #[serde(rename = "Swift-exception")]
    SwiftException,
    #[serde(rename = "u-boot-exception-2.0")]
    UBootException2Period0,
    #[serde(rename = "Universal-FOSS-exception-1.0")]
    UniversalFossException1Period0,
    #[serde(rename = "WxWindows-exception-3.1")]
    WxWindowsException3Period1,

}

impl ToString for SpdxPeriodSchema {
    fn to_string(&self) -> String {
        match self {
            Self::Afl2Period0 => String::from("AFL-2.0"),
            Self::Aal => String::from("AAL"),
            Self::Adobe2006 => String::from("Adobe-2006"),
            Self::Afl3Period0 => String::from("AFL-3.0"),
            Self::Adsl => String::from("ADSL"),
            Self::Variant0Bsd => String::from("0BSD"),
            Self::Afmparse => String::from("Afmparse"),
            Self::Afl1Period2 => String::from("AFL-1.2"),
            Self::Agpl1Period0OrLater => String::from("AGPL-1.0-or-later"),
            Self::Afl2Period1 => String::from("AFL-2.1"),
            Self::Afl1Period1 => String::from("AFL-1.1"),
            Self::Agpl1Period0 => String::from("AGPL-1.0"),
            Self::AdobeGlyph => String::from("Adobe-Glyph"),
            Self::Amdplpa => String::from("AMDPLPA"),
            Self::Aladdin => String::from("Aladdin"),
            Self::AntlrPd => String::from("ANTLR-PD"),
            Self::Aml => String::from("AML"),
            Self::Apache1Period0 => String::from("Apache-1.0"),
            Self::AntlrPdFallback => String::from("ANTLR-PD-fallback"),
            Self::Abstyles => String::from("Abstyles"),
            Self::Agpl1Period0Only => String::from("AGPL-1.0-only"),
            Self::Apafml => String::from("APAFML"),
            Self::Apsl1Period0 => String::from("APSL-1.0"),
            Self::Apsl1Period1 => String::from("APSL-1.1"),
            Self::Apsl2Period0 => String::from("APSL-2.0"),
            Self::Agpl3Period0Only => String::from("AGPL-3.0-only"),
            Self::Apache1Period1 => String::from("Apache-1.1"),
            Self::Apache2Period0 => String::from("Apache-2.0"),
            Self::Apl1Period0 => String::from("APL-1.0"),
            Self::Bahyph => String::from("Bahyph"),
            Self::Artistic1Period0 => String::from("Artistic-1.0"),
            Self::Ampas => String::from("AMPAS"),
            Self::Barr => String::from("Barr"),
            Self::Agpl3Period0OrLater => String::from("AGPL-3.0-or-later"),
            Self::BlueOak1Period0Period0 => String::from("BlueOak-1.0.0"),
            Self::Beerware => String::from("Beerware"),
            Self::Artistic1Period0Cl8 => String::from("Artistic-1.0-cl8"),
            Self::Blessing => String::from("blessing"),
            Self::Borceux => String::from("Borceux"),
            Self::Bsd2ClauseNetBsd => String::from("BSD-2-Clause-NetBSD"),
            Self::Bsd1Clause => String::from("BSD-1-Clause"),
            Self::Bsd2ClausePatent => String::from("BSD-2-Clause-Patent"),
            Self::BitTorrent1Period0 => String::from("BitTorrent-1.0"),
            Self::Bsd2ClauseFreeBsd => String::from("BSD-2-Clause-FreeBSD"),
            Self::Bsd3ClauseAttribution => String::from("BSD-3-Clause-Attribution"),
            Self::Bsd2Clause => String::from("BSD-2-Clause"),
            Self::Apsl1Period2 => String::from("APSL-1.2"),
            Self::Bsd3ClauseLbnl => String::from("BSD-3-Clause-LBNL"),
            Self::Artistic2Period0 => String::from("Artistic-2.0"),
            Self::Bsd3ClauseNoNuclearLicense2014 => String::from("BSD-3-Clause-No-Nuclear-License-2014"),
            Self::Bsd3ClauseModification => String::from("BSD-3-Clause-Modification"),
            Self::Bsd4ClauseShortened => String::from("BSD-4-Clause-Shortened"),
            Self::Bsd3Clause => String::from("BSD-3-Clause"),
            Self::Bsd3ClauseOpenMpi => String::from("BSD-3-Clause-Open-MPI"),
            Self::BitTorrent1Period1 => String::from("BitTorrent-1.1"),
            Self::Bsd3ClauseNoNuclearWarranty => String::from("BSD-3-Clause-No-Nuclear-Warranty"),
            Self::BsdSourceCode => String::from("BSD-Source-Code"),
            Self::BsdProtection => String::from("BSD-Protection"),
            Self::Agpl3Period0 => String::from("AGPL-3.0"),
            Self::Busl1Period1 => String::from("BUSL-1.1"),
            Self::Artistic1Period0Perl => String::from("Artistic-1.0-Perl"),
            Self::Bsl1Period0 => String::from("BSL-1.0"),
            Self::Bsd2ClauseViews => String::from("BSD-2-Clause-Views"),
            Self::Cal1Period0CombinedWorkException => String::from("CAL-1.0-Combined-Work-Exception"),
            Self::Catosl1Period1 => String::from("CATOSL-1.1"),
            Self::Bzip21Period0Period5 => String::from("bzip2-1.0.5"),
            Self::Bzip21Period0Period6 => String::from("bzip2-1.0.6"),
            Self::CcBy2Period5 => String::from("CC-BY-2.5"),
            Self::CcBy3Period0At => String::from("CC-BY-3.0-AT"),
            Self::CUda1Period0 => String::from("C-UDA-1.0"),
            Self::CcBy3Period0Us => String::from("CC-BY-3.0-US"),
            Self::CcBy1Period0 => String::from("CC-BY-1.0"),
            Self::CcByNc1Period0 => String::from("CC-BY-NC-1.0"),
            Self::CcByNc2Period0 => String::from("CC-BY-NC-2.0"),
            Self::CcByNc2Period5 => String::from("CC-BY-NC-2.5"),
            Self::CcBy2Period0 => String::from("CC-BY-2.0"),
            Self::CcByNc4Period0 => String::from("CC-BY-NC-4.0"),
            Self::CcByNcNd1Period0 => String::from("CC-BY-NC-ND-1.0"),
            Self::CcByNcNd2Period0 => String::from("CC-BY-NC-ND-2.0"),
            Self::CcByNc3Period0 => String::from("CC-BY-NC-3.0"),
            Self::CcByNcNd3Period0Igo => String::from("CC-BY-NC-ND-3.0-IGO"),
            Self::CcByNcNd3Period0 => String::from("CC-BY-NC-ND-3.0"),
            Self::Bsd3ClauseNoNuclearLicense => String::from("BSD-3-Clause-No-Nuclear-License"),
            Self::CcByNcNd4Period0 => String::from("CC-BY-NC-ND-4.0"),
            Self::CcByNcSa2Period0 => String::from("CC-BY-NC-SA-2.0"),
            Self::CcByNcSa2Period5 => String::from("CC-BY-NC-SA-2.5"),
            Self::CcByNcSa3Period0 => String::from("CC-BY-NC-SA-3.0"),
            Self::CcByNcSa4Period0 => String::from("CC-BY-NC-SA-4.0"),
            Self::CcByNd1Period0 => String::from("CC-BY-ND-1.0"),
            Self::Bsd3ClauseClear => String::from("BSD-3-Clause-Clear"),
            Self::CcByNd2Period5 => String::from("CC-BY-ND-2.5"),
            Self::CcByNd3Period0 => String::from("CC-BY-ND-3.0"),
            Self::CcByNd4Period0 => String::from("CC-BY-ND-4.0"),
            Self::CcBySa1Period0 => String::from("CC-BY-SA-1.0"),
            Self::CcBySa2Period0Uk => String::from("CC-BY-SA-2.0-UK"),
            Self::CcBySa2Period0 => String::from("CC-BY-SA-2.0"),
            Self::CcBySa2Period1Jp => String::from("CC-BY-SA-2.1-JP"),
            Self::CcByNd2Period0 => String::from("CC-BY-ND-2.0"),
            Self::CcBySa3Period0At => String::from("CC-BY-SA-3.0-AT"),
            Self::CcBySa3Period0 => String::from("CC-BY-SA-3.0"),
            Self::CcBySa4Period0 => String::from("CC-BY-SA-4.0"),
            Self::CcBySa2Period5 => String::from("CC-BY-SA-2.5"),
            Self::CcBy3Period0 => String::from("CC-BY-3.0"),
            Self::Cddl1Period0 => String::from("CDDL-1.0"),
            Self::Cc01Period0 => String::from("CC0-1.0"),
            Self::CcByNcNd2Period5 => String::from("CC-BY-NC-ND-2.5"),
            Self::CcByNcSa1Period0 => String::from("CC-BY-NC-SA-1.0"),
            Self::Caldera => String::from("Caldera"),
            Self::CdlaPermissive1Period0 => String::from("CDLA-Permissive-1.0"),
            Self::CcBy4Period0 => String::from("CC-BY-4.0"),
            Self::CcPddc => String::from("CC-PDDC"),
            Self::Bsd4ClauseUc => String::from("BSD-4-Clause-UC"),
            Self::Bsd4Clause => String::from("BSD-4-Clause"),
            Self::Cal1Period0 => String::from("CAL-1.0"),
            Self::Cddl1Period1 => String::from("CDDL-1.1"),
            Self::CernOhl1Period2 => String::from("CERN-OHL-1.2"),
            Self::CernOhl1Period1 => String::from("CERN-OHL-1.1"),
            Self::CernOhlP2Period0 => String::from("CERN-OHL-P-2.0"),
            Self::CernOhlS2Period0 => String::from("CERN-OHL-S-2.0"),
            Self::Cecill1Period1 => String::from("CECILL-1.1"),
            Self::Cecill2Period0 => String::from("CECILL-2.0"),
            Self::Cecill1Period0 => String::from("CECILL-1.0"),
            Self::CnriPython => String::from("CNRI-Python"),
            Self::CnriPythonGplCompatible => String::from("CNRI-Python-GPL-Compatible"),
            Self::CopyleftNext0Period3Period0 => String::from("copyleft-next-0.3.0"),
            Self::Cpal1Period0 => String::from("CPAL-1.0"),
            Self::CopyleftNext0Period3Period1 => String::from("copyleft-next-0.3.1"),
            Self::Cpl1Period0 => String::from("CPL-1.0"),
            Self::ClArtistic => String::from("ClArtistic"),
            Self::CecillC => String::from("CECILL-C"),
            Self::CnriJython => String::from("CNRI-Jython"),
            Self::Condor1Period1 => String::from("Condor-1.1"),
            Self::Cpol1Period02 => String::from("CPOL-1.02"),
            Self::Curl => String::from("curl"),
            Self::Diffmark => String::from("diffmark"),
            Self::Crossword => String::from("Crossword"),
            Self::Dotseqn => String::from("Dotseqn"),
            Self::Doc => String::from("DOC"),
            Self::Dsdp => String::from("DSDP"),
            Self::Drl1Period0 => String::from("DRL-1.0"),
            Self::Ecl1Period0 => String::from("ECL-1.0"),
            Self::Ecl2Period0 => String::from("ECL-2.0"),
            Self::ECos2Period0 => String::from("eCos-2.0"),
            Self::CrystalStacker => String::from("CrystalStacker"),
            Self::CernOhlW2Period0 => String::from("CERN-OHL-W-2.0"),
            Self::DFsl1Period0 => String::from("D-FSL-1.0"),
            Self::EGenix => String::from("eGenix"),
            Self::Epics => String::from("EPICS"),
            Self::Entessa => String::from("Entessa"),
            Self::Epl1Period0 => String::from("EPL-1.0"),
            Self::Efl2Period0 => String::from("EFL-2.0"),
            Self::CuaOpl1Period0 => String::from("CUA-OPL-1.0"),
            Self::Etalab2Period0 => String::from("etalab-2.0"),
            Self::Eupl1Period0 => String::from("EUPL-1.0"),
            Self::ErlPl1Period1 => String::from("ErlPL-1.1"),
            Self::EuDatagrid => String::from("EUDatagrid"),
            Self::Eupl1Period1 => String::from("EUPL-1.1"),
            Self::Cube => String::from("Cube"),
            Self::Dvipdfm => String::from("dvipdfm"),
            Self::FreeBsdDoc => String::from("FreeBSD-DOC"),
            Self::Eurosym => String::from("Eurosym"),
            Self::Fsfap => String::from("FSFAP"),
            Self::FreeImage => String::from("FreeImage"),
            Self::Fsfullr => String::from("FSFULLR"),
            Self::Fsful => String::from("FSFUL"),
            Self::Gd => String::from("GD"),
            Self::Gfdl1Period1InvariantsOnly => String::from("GFDL-1.1-invariants-only"),
            Self::Eupl1Period2 => String::from("EUPL-1.2"),
            Self::Epl2Period0 => String::from("EPL-2.0"),
            Self::Gfdl1Period1NoInvariantsOrLater => String::from("GFDL-1.1-no-invariants-or-later"),
            Self::Gfdl1Period1Only => String::from("GFDL-1.1-only"),
            Self::Gfdl1Period1OrLater => String::from("GFDL-1.1-or-later"),
            Self::Gfdl1Period1 => String::from("GFDL-1.1"),
            Self::Ftl => String::from("FTL"),
            Self::Gfdl1Period2InvariantsOrLater => String::from("GFDL-1.2-invariants-or-later"),
            Self::Gfdl1Period1InvariantsOrLater => String::from("GFDL-1.1-invariants-or-later"),
            Self::Gfdl1Period2InvariantsOnly => String::from("GFDL-1.2-invariants-only"),
            Self::Gfdl1Period2Only => String::from("GFDL-1.2-only"),
            Self::Gfdl1Period2OrLater => String::from("GFDL-1.2-or-later"),
            Self::Gfdl1Period2 => String::from("GFDL-1.2"),
            Self::Gfdl1Period2NoInvariantsOnly => String::from("GFDL-1.2-no-invariants-only"),
            Self::Gfdl1Period3InvariantsOnly => String::from("GFDL-1.3-invariants-only"),
            Self::Gfdl1Period3NoInvariantsOnly => String::from("GFDL-1.3-no-invariants-only"),
            Self::Gfdl1Period3InvariantsOrLater => String::from("GFDL-1.3-invariants-or-later"),
            Self::Gfdl1Period2NoInvariantsOrLater => String::from("GFDL-1.2-no-invariants-or-later"),
            Self::Fair => String::from("Fair"),
            Self::Frameworx1Period0 => String::from("Frameworx-1.0"),
            Self::Giftware => String::from("Giftware"),
            Self::Gfdl1Period1NoInvariantsOnly => String::from("GFDL-1.1-no-invariants-only"),
            Self::Gl2Ps => String::from("GL2PS"),
            Self::Glulxe => String::from("Glulxe"),
            Self::Glide => String::from("Glide"),
            Self::Gnuplot => String::from("gnuplot"),
            Self::Glwtpl => String::from("GLWTPL"),
            Self::Gpl1Period0Only => String::from("GPL-1.0-only"),
            Self::Gpl1Period0OrLater => String::from("GPL-1.0-or-later"),
            Self::Gpl1Period0 => String::from("GPL-1.0"),
            Self::Gfdl1Period3Only => String::from("GFDL-1.3-only"),
            Self::Gpl2Period0Only => String::from("GPL-2.0-only"),
            Self::Gpl2Period0OrLater => String::from("GPL-2.0-or-later"),
            Self::Gpl2Period0WithAutoconfException => String::from("GPL-2.0-with-autoconf-exception"),
            Self::Gpl2Period0Plus => String::from("GPL-2.0+"),
            Self::Gfdl1Period3 => String::from("GFDL-1.3"),
            Self::Gpl1Period0Plus => String::from("GPL-1.0+"),
            Self::CdlaSharing1Period0 => String::from("CDLA-Sharing-1.0"),
            Self::Gpl2Period0WithClasspathException => String::from("GPL-2.0-with-classpath-exception"),
            Self::Gpl2Period0WithGccException => String::from("GPL-2.0-with-GCC-exception"),
            Self::Gpl2Period0WithBisonException => String::from("GPL-2.0-with-bison-exception"),
            Self::Gpl2Period0WithFontException => String::from("GPL-2.0-with-font-exception"),
            Self::Gpl2Period0 => String::from("GPL-2.0"),
            Self::Cecill2Period1 => String::from("CECILL-2.1"),
            Self::Gpl3Period0 => String::from("GPL-3.0"),
            Self::Gpl3Period0Plus => String::from("GPL-3.0+"),
            Self::Gpl3Period0WithAutoconfException => String::from("GPL-3.0-with-autoconf-exception"),
            Self::Gpl3Period0Only => String::from("GPL-3.0-only"),
            Self::Hippocratic2Period1 => String::from("Hippocratic-2.1"),
            Self::Hpnd => String::from("HPND"),
            Self::Htmltidy => String::from("HTMLTIDY"),
            Self::Gpl3Period0WithGccException => String::from("GPL-3.0-with-GCC-exception"),
            Self::HaskellReport => String::from("HaskellReport"),
            Self::Gpl3Period0OrLater => String::from("GPL-3.0-or-later"),
            Self::Icu => String::from("ICU"),
            Self::ImageMagick => String::from("ImageMagick"),
            Self::IMatix => String::from("iMatix"),
            Self::IbmPibs => String::from("IBM-pibs"),
            Self::IntelAcpi => String::from("Intel-ACPI"),
            Self::Intel => String::from("Intel"),
            Self::InfoZip => String::from("Info-ZIP"),
            Self::Ipa => String::from("IPA"),
            Self::Ijg => String::from("IJG"),
            Self::Isc => String::from("ISC"),
            Self::JasPer2Period0 => String::from("JasPer-2.0"),
            Self::Jpnic => String::from("JPNIC"),
            Self::Json => String::from("JSON"),
            Self::Lal1Period2 => String::from("LAL-1.2"),
            Self::Lal1Period3 => String::from("LAL-1.3"),
            Self::Latex2e => String::from("Latex2e"),
            Self::Leptonica => String::from("Leptonica"),
            Self::HpndSellVariant => String::from("HPND-sell-variant"),
            Self::Lgpl2Period0Only => String::from("LGPL-2.0-only"),
            Self::Lgpl2Period0OrLater => String::from("LGPL-2.0-or-later"),
            Self::Imlib2 => String::from("Imlib2"),
            Self::Ipl1Period0 => String::from("IPL-1.0"),
            Self::Lgpl2Period1Only => String::from("LGPL-2.1-only"),
            Self::Lgpl2Period1OrLater => String::from("LGPL-2.1-or-later"),
            Self::Lgpl2Period0Plus => String::from("LGPL-2.0+"),
            Self::Lgpl2Period0 => String::from("LGPL-2.0"),
            Self::CecillB => String::from("CECILL-B"),
            Self::Lgpl3Period0OrLater => String::from("LGPL-3.0-or-later"),
            Self::Lgpl3Period0Only => String::from("LGPL-3.0-only"),
            Self::Lgpllr => String::from("LGPLLR"),
            Self::Libpng2Period0 => String::from("libpng-2.0"),
            Self::Libpng => String::from("Libpng"),
            Self::Libselinux1Period0 => String::from("libselinux-1.0"),
            Self::Lgpl3Period0Plus => String::from("LGPL-3.0+"),
            Self::Efl1Period0 => String::from("EFL-1.0"),
            Self::Libtiff => String::from("libtiff"),
            Self::Gfdl1Period3NoInvariantsOrLater => String::from("GFDL-1.3-no-invariants-or-later"),
            Self::LiLiQRplus1Period1 => String::from("LiLiQ-Rplus-1.1"),
            Self::LiLiQR1Period1 => String::from("LiLiQ-R-1.1"),
            Self::Lpl1Period0 => String::from("LPL-1.0"),
            Self::LiLiQP1Period1 => String::from("LiLiQ-P-1.1"),
            Self::LinuxOpenIb => String::from("Linux-OpenIB"),
            Self::Lppl1Period0 => String::from("LPPL-1.0"),
            Self::Lppl1Period2 => String::from("LPPL-1.2"),
            Self::Lppl1Period3a => String::from("LPPL-1.3a"),
            Self::Lpl1Period02 => String::from("LPL-1.02"),
            Self::Lppl1Period3c => String::from("LPPL-1.3c"),
            Self::MakeIndex => String::from("MakeIndex"),
            Self::Lgpl2Period1Plus => String::from("LGPL-2.1+"),
            Self::Lppl1Period1 => String::from("LPPL-1.1"),
            Self::MitCmu => String::from("MIT-CMU"),
            Self::MirOs => String::from("MirOS"),
            Self::MitAdvertising => String::from("MIT-advertising"),
            Self::MitModernVariant => String::from("MIT-Modern-Variant"),
            Self::Mit => String::from("MIT"),
            Self::MitEnna => String::from("MIT-enna"),
            Self::MitOpenGroup => String::from("MIT-open-group"),
            Self::MitFeh => String::from("MIT-feh"),
            Self::Mitnfa => String::from("MITNFA"),
            Self::Mpl1Period0 => String::from("MPL-1.0"),
            Self::Mpich2 => String::from("mpich2"),
            Self::Mpl2Period0 => String::from("MPL-2.0"),
            Self::Mpl2Period0NoCopyleftException => String::from("MPL-2.0-no-copyleft-exception"),
            Self::MsRl => String::from("MS-RL"),
            Self::Mtll => String::from("MTLL"),
            Self::Mpl1Period1 => String::from("MPL-1.1"),
            Self::MulanPsl2Period0 => String::from("MulanPSL-2.0"),
            Self::Motosoto => String::from("Motosoto"),
            Self::Mup => String::from("Mup"),
            Self::MulanPsl1Period0 => String::from("MulanPSL-1.0"),
            Self::Naist2003 => String::from("NAIST-2003"),
            Self::Naumen => String::from("Naumen"),
            Self::Multics => String::from("Multics"),
            Self::Nbpl1Period0 => String::from("NBPL-1.0"),
            Self::Ncsa => String::from("NCSA"),
            Self::NetSnmp => String::from("Net-SNMP"),
            Self::NetCdf => String::from("NetCDF"),
            Self::Nasa1Period3 => String::from("NASA-1.3"),
            Self::Ngpl => String::from("NGPL"),
            Self::NistPdFallback => String::from("NIST-PD-fallback"),
            Self::NistPd => String::from("NIST-PD"),
            Self::Newsletr => String::from("Newsletr"),
            Self::Nlpl => String::from("NLPL"),
            Self::Nokia => String::from("Nokia"),
            Self::Nosl => String::from("NOSL"),
            Self::Noweb => String::from("Noweb"),
            Self::Nlod1Period0 => String::from("NLOD-1.0"),
            Self::Npl1Period0 => String::from("NPL-1.0"),
            Self::NcglUk2Period0 => String::from("NCGL-UK-2.0"),
            Self::Nrl => String::from("NRL"),
            Self::Ntp0 => String::from("NTP-0"),
            Self::Ntp => String::from("NTP"),
            Self::Gfdl1Period3OrLater => String::from("GFDL-1.3-or-later"),
            Self::Nunit => String::from("Nunit"),
            Self::OUda1Period0 => String::from("O-UDA-1.0"),
            Self::Npl1Period1 => String::from("NPL-1.1"),
            Self::OcctPl => String::from("OCCT-PL"),
            Self::OdcBy1Period0 => String::from("ODC-By-1.0"),
            Self::Ofl1Period0NoRfn => String::from("OFL-1.0-no-RFN"),
            Self::Oclc2Period0 => String::from("OCLC-2.0"),
            Self::Ofl1Period0Rfn => String::from("OFL-1.0-RFN"),
            Self::Ofl1Period0 => String::from("OFL-1.0"),
            Self::Ofl1Period1NoRfn => String::from("OFL-1.1-no-RFN"),
            Self::Ofl1Period1Rfn => String::from("OFL-1.1-RFN"),
            Self::Ofl1Period1 => String::from("OFL-1.1"),
            Self::OgdlTaiwan1Period0 => String::from("OGDL-Taiwan-1.0"),
            Self::Ogc1Period0 => String::from("OGC-1.0"),
            Self::OglUk1Period0 => String::from("OGL-UK-1.0"),
            Self::OglUk2Period0 => String::from("OGL-UK-2.0"),
            Self::OglUk3Period0 => String::from("OGL-UK-3.0"),
            Self::Ogtsl => String::from("OGTSL"),
            Self::Oldap1Period1 => String::from("OLDAP-1.1"),
            Self::Oldap1Period2 => String::from("OLDAP-1.2"),
            Self::Oldap1Period3 => String::from("OLDAP-1.3"),
            Self::OglCanada2Period0 => String::from("OGL-Canada-2.0"),
            Self::Oldap2Period0Period1 => String::from("OLDAP-2.0.1"),
            Self::Oldap2Period0 => String::from("OLDAP-2.0"),
            Self::Oldap2Period1 => String::from("OLDAP-2.1"),
            Self::Oldap2Period2Period1 => String::from("OLDAP-2.2.1"),
            Self::Oldap2Period2Period2 => String::from("OLDAP-2.2.2"),
            Self::Oldap2Period2 => String::from("OLDAP-2.2"),
            Self::OdbL1Period0 => String::from("ODbL-1.0"),
            Self::Oldap2Period4 => String::from("OLDAP-2.4"),
            Self::Oldap1Period4 => String::from("OLDAP-1.4"),
            Self::Oldap2Period3 => String::from("OLDAP-2.3"),
            Self::Oldap2Period7 => String::from("OLDAP-2.7"),
            Self::Oldap2Period8 => String::from("OLDAP-2.8"),
            Self::Oml => String::from("OML"),
            Self::OpenSsl => String::from("OpenSSL"),
            Self::Oldap2Period6 => String::from("OLDAP-2.6"),
            Self::Opl1Period0 => String::from("OPL-1.0"),
            Self::Osl1Period0 => String::from("OSL-1.0"),
            Self::Osl1Period1 => String::from("OSL-1.1"),
            Self::Osl2Period0 => String::from("OSL-2.0"),
            Self::OsetPl2Period1 => String::from("OSET-PL-2.1"),
            Self::Osl2Period1 => String::from("OSL-2.1"),
            Self::Parity6Period0Period0 => String::from("Parity-6.0.0"),
            Self::Parity7Period0Period0 => String::from("Parity-7.0.0"),
            Self::Pddl1Period0 => String::from("PDDL-1.0"),
            Self::Php3Period0 => String::from("PHP-3.0"),
            Self::Osl3Period0 => String::from("OSL-3.0"),
            Self::Plexus => String::from("Plexus"),
            Self::MsPl => String::from("MS-PL"),
            Self::PolyFormSmallBusiness1Period0Period0 => String::from("PolyForm-Small-Business-1.0.0"),
            Self::PolyFormNoncommercial1Period0Period0 => String::from("PolyForm-Noncommercial-1.0.0"),
            Self::Psf2Period0 => String::from("PSF-2.0"),
            Self::Psfrag => String::from("psfrag"),
            Self::PostgreSql => String::from("PostgreSQL"),
            Self::Psutils => String::from("psutils"),
            Self::Qhull => String::from("Qhull"),
            Self::Qpl1Period0 => String::from("QPL-1.0"),
            Self::Rdisc => String::from("Rdisc"),
            Self::Python2Period0 => String::from("Python-2.0"),
            Self::Rpl1Period1 => String::from("RPL-1.1"),
            Self::Rpl1Period5 => String::from("RPL-1.5"),
            Self::RheCos1Period1 => String::from("RHeCos-1.1"),
            Self::RsaMd => String::from("RSA-MD"),
            Self::Rscpl => String::from("RSCPL"),
            Self::Ruby => String::from("Ruby"),
            Self::SaxPd => String::from("SAX-PD"),
            Self::Saxpath => String::from("Saxpath"),
            Self::Scea => String::from("SCEA"),
            Self::Sendmail8Period23 => String::from("Sendmail-8.23"),
            Self::Sendmail => String::from("Sendmail"),
            Self::SgiB1Period0 => String::from("SGI-B-1.0"),
            Self::SgiB1Period1 => String::from("SGI-B-1.1"),
            Self::SgiB2Period0 => String::from("SGI-B-2.0"),
            Self::Shl0Period5 => String::from("SHL-0.5"),
            Self::Shl0Period51 => String::from("SHL-0.51"),
            Self::SimPl2Period0 => String::from("SimPL-2.0"),
            Self::Sissl1Period2 => String::from("SISSL-1.2"),
            Self::Sissl => String::from("SISSL"),
            Self::Sleepycat => String::from("Sleepycat"),
            Self::Smlnj => String::from("SMLNJ"),
            Self::Smppl => String::from("SMPPL"),
            Self::Snia => String::from("SNIA"),
            Self::Spencer86 => String::from("Spencer-86"),
            Self::Spencer94 => String::from("Spencer-94"),
            Self::Spencer99 => String::from("Spencer-99"),
            Self::Spl1Period0 => String::from("SPL-1.0"),
            Self::SshOpenSsh => String::from("SSH-OpenSSH"),
            Self::Php3Period01 => String::from("PHP-3.01"),
            Self::SshShort => String::from("SSH-short"),
            Self::Mit0 => String::from("MIT-0"),
            Self::Rpsl1Period0 => String::from("RPSL-1.0"),
            Self::Swl => String::from("SWL"),
            Self::SugarCrm1Period1Period3 => String::from("SugarCRM-1.1.3"),
            Self::Tcl => String::from("TCL"),
            Self::TcpWrappers => String::from("TCP-wrappers"),
            Self::Sspl1Period0 => String::from("SSPL-1.0"),
            Self::TMate => String::from("TMate"),
            Self::Tosl => String::from("TOSL"),
            Self::Torque1Period1 => String::from("TORQUE-1.1"),
            Self::TaprOhl1Period0 => String::from("TAPR-OHL-1.0"),
            Self::Ucl1Period0 => String::from("UCL-1.0"),
            Self::UnicodeDfs2015 => String::from("Unicode-DFS-2015"),
            Self::UnicodeDfs2016 => String::from("Unicode-DFS-2016"),
            Self::UnicodeTou => String::from("Unicode-TOU"),
            Self::TuBerlin1Period0 => String::from("TU-Berlin-1.0"),
            Self::Upl1Period0 => String::from("UPL-1.0"),
            Self::Unlicense => String::from("Unlicense"),
            Self::Vostrom => String::from("VOSTROM"),
            Self::Vim => String::from("Vim"),
            Self::Vsl1Period0 => String::from("VSL-1.0"),
            Self::W3C20150513 => String::from("W3C-20150513"),
            Self::W3C => String::from("W3C"),
            Self::W3C19980720 => String::from("W3C-19980720"),
            Self::Wsuipa => String::from("Wsuipa"),
            Self::Watcom1Period0 => String::from("Watcom-1.0"),
            Self::Wtfpl => String::from("WTFPL"),
            Self::X11 => String::from("X11"),
            Self::Xerox => String::from("Xerox"),
            Self::XFree861Period1 => String::from("XFree86-1.1"),
            Self::Xinetd => String::from("xinetd"),
            Self::Xnet => String::from("Xnet"),
            Self::Xpp => String::from("xpp"),
            Self::XSkat => String::from("XSkat"),
            Self::Ypl1Period0 => String::from("YPL-1.0"),
            Self::Ypl1Period1 => String::from("YPL-1.1"),
            Self::Zed => String::from("Zed"),
            Self::Zend2Period0 => String::from("Zend-2.0"),
            Self::TuBerlin2Period0 => String::from("TU-Berlin-2.0"),
            Self::Zimbra1Period4 => String::from("Zimbra-1.4"),
            Self::ZlibAcknowledgement => String::from("zlib-acknowledgement"),
            Self::Zlib => String::from("Zlib"),
            Self::Zpl1Period1 => String::from("ZPL-1.1"),
            Self::Zpl2Period0 => String::from("ZPL-2.0"),
            Self::Zpl2Period1 => String::from("ZPL-2.1"),
            Self::WxWindows => String::from("wxWindows"),
            Self::Zimbra1Period3 => String::from("Zimbra-1.3"),
            Self::GSoap1Period3b => String::from("gSOAP-1.3b"),
            Self::Interbase1Period0 => String::from("Interbase-1.0"),
            Self::Lgpl2Period1 => String::from("LGPL-2.1"),
            Self::Lgpl3Period0 => String::from("LGPL-3.0"),
            Self::Nposl3Period0 => String::from("NPOSL-3.0"),
            Self::Oldap2Period5 => String::from("OLDAP-2.5"),
            Self::StandardMlNj => String::from("StandardML-NJ"),
            Self::Variant389Exception => String::from("389-exception"),
            Self::AutoconfException2Period0 => String::from("Autoconf-exception-2.0"),
            Self::AutoconfException3Period0 => String::from("Autoconf-exception-3.0"),
            Self::BisonException2Period2 => String::from("Bison-exception-2.2"),
            Self::BootloaderException => String::from("Bootloader-exception"),
            Self::ClasspathException2Period0 => String::from("Classpath-exception-2.0"),
            Self::ClispException2Period0 => String::from("CLISP-exception-2.0"),
            Self::DigiRuleFossException => String::from("DigiRule-FOSS-exception"),
            Self::ECosException2Period0 => String::from("eCos-exception-2.0"),
            Self::FawkesRuntimeException => String::from("Fawkes-Runtime-exception"),
            Self::FltkException => String::from("FLTK-exception"),
            Self::FontException2Period0 => String::from("Font-exception-2.0"),
            Self::FreertosException2Period0 => String::from("freertos-exception-2.0"),
            Self::GccException2Period0 => String::from("GCC-exception-2.0"),
            Self::GccException3Period1 => String::from("GCC-exception-3.1"),
            Self::GnuJavamailException => String::from("gnu-javamail-exception"),
            Self::Gpl3Period0LinkingException => String::from("GPL-3.0-linking-exception"),
            Self::Gpl3Period0LinkingSourceException => String::from("GPL-3.0-linking-source-exception"),
            Self::GplCc1Period0 => String::from("GPL-CC-1.0"),
            Self::I2pGplJavaException => String::from("i2p-gpl-java-exception"),
            Self::Lgpl3Period0LinkingException => String::from("LGPL-3.0-linking-exception"),
            Self::LibtoolException => String::from("Libtool-exception"),
            Self::LinuxSyscallNote => String::from("Linux-syscall-note"),
            Self::LlvmException => String::from("LLVM-exception"),
            Self::LzmaException => String::from("LZMA-exception"),
            Self::MifException => String::from("mif-exception"),
            Self::NokiaQtException1Period1 => String::from("Nokia-Qt-exception-1.1"),
            Self::OCamlLgplLinkingException => String::from("OCaml-LGPL-linking-exception"),
            Self::OcctException1Period0 => String::from("OCCT-exception-1.0"),
            Self::OpenJdkAssemblyException1Period0 => String::from("OpenJDK-assembly-exception-1.0"),
            Self::OpenvpnOpensslException => String::from("openvpn-openssl-exception"),
            Self::PsOrPdfFontException20170817 => String::from("PS-or-PDF-font-exception-20170817"),
            Self::QtGplException1Period0 => String::from("Qt-GPL-exception-1.0"),
            Self::QtLgplException1Period1 => String::from("Qt-LGPL-exception-1.1"),
            Self::QwtException1Period0 => String::from("Qwt-exception-1.0"),
            Self::Shl2Period0 => String::from("SHL-2.0"),
            Self::Shl2Period1 => String::from("SHL-2.1"),
            Self::SwiftException => String::from("Swift-exception"),
            Self::UBootException2Period0 => String::from("u-boot-exception-2.0"),
            Self::UniversalFossException1Period0 => String::from("Universal-FOSS-exception-1.0"),
            Self::WxWindowsException3Period1 => String::from("WxWindows-exception-3.1"),
        }
    }
}

impl Default for SpdxPeriodSchema {
    fn default() -> SpdxPeriodSchema {
        Self::Afl2Period0
    }
}




