use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Copyright {
    #[serde(rename = "text")]
    pub text: String,
}

impl Copyright {
    pub fn new(text: String) -> Copyright {
        Copyright { text }
    }
}
