use serde::{Deserialize, Serialize};
/*
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LicenseChoice {
    #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
    pub license: Option<Box<crate::entities::cyclonedx::models::License>>,
    #[serde(rename = "expression", skip_serializing_if = "Option::is_none")]
    pub expression: Option<String>,
}

impl LicenseChoice {
    pub fn new() -> LicenseChoice {
        LicenseChoice {
            license: None,
            expression: None,
        }
    }
}
