name: Test UI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

defaults:
  run:
    working-directory: ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Gen SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          path: ./
          artifact-name: sbom-harbor-frontend.json
          format: cyclonedx-json

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.0'
          registry-url: 'https://registry.npmjs.org'
        #   cache: 'yarn'
      - run: |
            yarn set version 3.2.2
            yarn config set -H enableImmutableInstalls false
      - run: yarn install
      - run: yarn lint
      - run: yarn test
