---

name: Push Event

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry run install

      - name: Build Code
        run: |
          poetry run build

      - name: Test with pytest
        run: |
          poetry run test

      - name: Package for Lambda
        run: |
          poetry run package
