name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize


env:
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1

jobs:
  backend:
    runs-on: [self-hosted,dev]
    steps:

      - uses: actions/checkout@v3

      - name: INSTALL - project
        run: poetry install --no-interaction

      - name: TEST - unit
        run: python -m pytest -v --cov=cyclonedx/ tests/

  frontend:
    runs-on: [self-hosted,dev]
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v3

      - name: Debug
        run: |
          echo "node --version: $(node --version)"
          echo "npm --version: $(npm --version)"
          echo "yarn --version: $(yarn --version)"

      - name: cache .yarn/
        id: cache-yarn-cache
        uses: actions/cache@v3
        with:
          path: .yarn/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: cache node_modules/
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Run yarn install
        run: CI=true yarn install

      - run: yarn lint

      - run: yarn test
