name: TESTS - Lint and Unit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

# Rather counterintuitive, concurrency is used to ensure that a workflow runs *singularly* per pull request.
# When a PR is updated, cancel any currently running workflows triggered by previous pushes,
# as they are essentially redundant and made moot by later pushes
# This will ensure that workflows do not block runners by executing unnecessarily
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1

jobs:
  backend:
    runs-on: [self-hosted,dev]
    steps:

      - uses: actions/checkout@v3

        # disable virtual environment to reuse cache between workflow runs
      - name: CONFIG - virtual environment
        run: poetry config virtualenvs.create false

      - name: INSTALL - project
        run: poetry install --no-interaction

      - name: TEST - lint
        run: pylint --rcfile ./.pylintrc cyclonedx/ || pylint-exit $?

      - name: TEST - unit
        run: python -m pytest -v --cov=cyclonedx/ tests/

  frontend:
    runs-on: [self-hosted,dev]

    defaults:
      run:
        working-directory: ui

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18.0.0"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/checkout@v3

      - name: Debug
        run: |
          echo "node --version: $(node --version)"
          echo "npm --version: $(npm --version)"
          echo "yarn --version: $(yarn --version)"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: cache .yarn/
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - name: Run yarn install
        run: CI=true yarn install

      - run: yarn lint

      - run: yarn test
