name: TESTS - Lint, Unit, Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

# Rather counterintuitive, concurrency is used to ensure that a workflow runs *singularly* per pull request.
# When a PR is updated, cancel any currently running workflows triggered by previous pushes,
# as they are essentially redundant and made moot by later pushes
# This will ensure that workflows do not block runners by executing unnecessarily
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1

jobs:
  backend:
    runs-on: [self-hosted]
    steps:

      - uses: actions/checkout@v3

      - name: INSTALL - dependencies
        run: cargo fetch

      - name: LINT
        run: cargo clippy -D warnings

      - name: TEST - unit & integration
        run: cargo test

  frontend:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v3

      - name: Debug
        run: |
          echo "node --version: $(node --version)"
          echo "npm --version: $(npm --version)"
          echo "yarn --version: $(yarn --version)"

      - name: cache .yarn/
        id: cache-yarn-cache
        uses: actions/cache@v3
        with:
          path: .yarn/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: cache node_modules/
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Run yarn install
        run: CI=true yarn install

      - run: yarn lint

      - run: yarn test
