name: TESTS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  backend:
    runs-on: ubuntu-latest
    container:
      image: aquia/rust-cargo-build-tools:1.68.0
    services:
      mongo:
        image: mongo:5.0.15
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: harbor
        options: >-
          --health-cmd "echo 'db.getMongo()' | mongo --norc --quiet --host=localhost:27017"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
            
      - name: INSTALL - dependencies
        run: cargo fetch

      - name: LINT
        run: cargo clippy -- -Dwarnings

      - name: TEST - unit & integration
        run: cargo test

  # frontend:
  #   runs-on: [self-hosted]
  #   defaults:
  #     run:
  #       working-directory: ui
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: DEBUG - node, npm, yarn versions
  #       run: |
  #         echo "node --version: $(node --version)"
  #         echo "npm --version: $(npm --version)"
  #         echo "yarn --version: $(yarn --version)"

  #     - name: CACHE - get ui cache path
  #       id: yarn-cache-dir-path
  #       run: echo "dir=$(yarn --cwd ui config get cacheFolder)" >> $GITHUB_OUTPUT

  #     - name: CACHE - ui dependencies
  #       id: yarn-cache
  #       uses: actions/cache@v3
  #       with:
  #         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #         key: yarn-cache-folder-${{ hashFiles('ui/**/yarn.lock', 'ui/.yarnrc.yml') }}
  #         restore-keys: |
  #           yarn-cache-folder-

  #     - name: INSTALL - ui dependencies
  #       working-directory: ui
  #       run: CI=true yarn install

  #     - name: LINT
  #       run: yarn lint

  #     - name: TEST - unit
  #       run: yarn test
